apiVersion: apps/v1
kind: Deployment
metadata:
  name: output-generation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: output-generation
  template:
    metadata:
      labels:
        app: output-generation
    spec:
      containers:
        - name: output-generation-container
          image: 376163012258.dkr.ecr.us-east-1.amazonaws.com/output-generation-app:latest
          ports:
            - containerPort : 8080
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: SMTP_PASSWORD


---
apiVersion: v1
kind: Service
metadata:
  name: output-generation-service
spec:
  selector:
    app: output-generation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

