name: Deploy Output Generation to EKS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 376163012258.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and push Docker image
        run: |
          docker build -t output-generation-app:latest .
          docker tag output-generation-app:latest 376163012258.dkr.ecr.us-east-1.amazonaws.com/output-generation-app:latest
          docker push 376163012258.dkr.ecr.us-east-1.amazonaws.com/output-generation-app:latest

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --name my-eks-cluster --region us-east-1

      - name: Debug Kubeconfig
        run: |
          echo "Checking Kubernetes context..."
          kubectl config view
          kubectl config current-context

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s-deployment.yaml